//! CoreML's protobuf schema, as Rust types.
//!
//! Generated by `tools/coreml-jigs`'s `gen-proto` binary from `proto/` and
//! committed here, so building Kohagi needs neither `protoc` nor a build script.
//! Regenerate with:
//!
//! ```console
//! cargo run --manifest-path tools/coreml-jigs/Cargo.toml --bin gen-proto
//! ```
//!
//! [`mil_spec`] is upstream `MIL.proto` unchanged. [`self`] is a trimmed subset of
//! `Model.proto` and `FeatureTypes.proto` — see `proto/CoreMLModelSubset.proto`
//! for what was left out and why, and [`roundtrip`] for the test that keeps the
//! subset honest.

// The generated code mirrors protobuf's naming, not Rust's, and describes the
// whole schema whether or not this crate touches every message yet. Both are
// properties of generated code rather than things to fix here.
#![allow(
    dead_code,
    clippy::doc_markdown,
    clippy::enum_variant_names,
    rustdoc::invalid_html_tags
)]

/// Upstream `MIL.proto`: the ML Program itself.
pub mod mil_spec {
    include!("generated/core_ml.specification.mil_spec.rs");
}

include!("generated/core_ml.specification.rs");

#[cfg(test)]
mod roundtrip;
